<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl\SLDeviceProto;

use UnexpectedValueException;

/**
 * Protobuf type <code>sl.SLDeviceProto.SLDeviceTypeProto</code>
 */
class SLDeviceTypeProto
{
    /**
     * Generated from protobuf enum <code>sl_sdi_device_type = 0;</code>
     */
    const sl_sdi_device_type = 0;
    /**
     * Generated from protobuf enum <code>sl_mpeg_ts_device_type = 1;</code>
     */
    const sl_mpeg_ts_device_type = 1;
    /**
     * Generated from protobuf enum <code>sl_es_device_type = 2;</code>
     */
    const sl_es_device_type = 2;

    private static $valueToName = [
        self::sl_sdi_device_type => 'sl_sdi_device_type',
        self::sl_mpeg_ts_device_type => 'sl_mpeg_ts_device_type',
        self::sl_es_device_type => 'sl_es_device_type',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SLDeviceTypeProto::class, \Sl\SLDeviceProto_SLDeviceTypeProto::class);

