version: '3'
services:
  php:
    image: php:fpm-alpine
    volumes:
      - './:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./conf/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=new
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin