version: '3'
services:
  php:
    image: sl-back:latest 
    #network_mode: "host"
    volumes:
      - './:/var/www/html'

  nginx:
    image: sl-front:latest
    #network_mode: "host"
    ports:
      - 8080:80
        #    volumes:
        # - './:/var/www/html'
        # - './docker/nginx/conf.d:/etc/nginx/conf.d'

  postgres:
    image: postgres:12
    #network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - ./conf/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=new
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
