<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace sl_logical_channel_description_proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_logical_channel_description_proto.logical_channel_proto</code>
 */
class logical_channel_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 service_id = 1;</code>
     */
    protected $service_id = 0;
    /**
     * Generated from protobuf field <code>uint32 visible_service_flag = 2;</code>
     */
    protected $visible_service_flag = 0;
    /**
     * Generated from protobuf field <code>uint32 logical_channel_number = 3;</code>
     */
    protected $logical_channel_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $service_id
     *     @type int $visible_service_flag
     *     @type int $logical_channel_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 service_id = 1;</code>
     * @return int
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>uint32 service_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkUint32($var);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 visible_service_flag = 2;</code>
     * @return int
     */
    public function getVisibleServiceFlag()
    {
        return $this->visible_service_flag;
    }

    /**
     * Generated from protobuf field <code>uint32 visible_service_flag = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVisibleServiceFlag($var)
    {
        GPBUtil::checkUint32($var);
        $this->visible_service_flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 logical_channel_number = 3;</code>
     * @return int
     */
    public function getLogicalChannelNumber()
    {
        return $this->logical_channel_number;
    }

    /**
     * Generated from protobuf field <code>uint32 logical_channel_number = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLogicalChannelNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->logical_channel_number = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(logical_channel_proto::class, \sl_logical_channel_description_proto_logical_channel_proto::class);

