<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_input_eit_proto</code>
 */
class sl_input_eit_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl_eit_proto actual = 1;</code>
     */
    protected $actual = null;
    /**
     * Generated from protobuf field <code>.sl_eit_proto actual_schedule = 2;</code>
     */
    protected $actual_schedule = null;
    /**
     * Generated from protobuf field <code>.sl_eit_proto other = 3;</code>
     */
    protected $other = null;
    /**
     * Generated from protobuf field <code>.sl_eit_proto other_schedule = 4;</code>
     */
    protected $other_schedule = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \sl_eit_proto $actual
     *     @type \sl_eit_proto $actual_schedule
     *     @type \sl_eit_proto $other
     *     @type \sl_eit_proto $other_schedule
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto actual = 1;</code>
     * @return \sl_eit_proto
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto actual = 1;</code>
     * @param \sl_eit_proto $var
     * @return $this
     */
    public function setActual($var)
    {
        GPBUtil::checkMessage($var, \sl_eit_proto::class);
        $this->actual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto actual_schedule = 2;</code>
     * @return \sl_eit_proto
     */
    public function getActualSchedule()
    {
        return $this->actual_schedule;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto actual_schedule = 2;</code>
     * @param \sl_eit_proto $var
     * @return $this
     */
    public function setActualSchedule($var)
    {
        GPBUtil::checkMessage($var, \sl_eit_proto::class);
        $this->actual_schedule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto other = 3;</code>
     * @return \sl_eit_proto
     */
    public function getOther()
    {
        return $this->other;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto other = 3;</code>
     * @param \sl_eit_proto $var
     * @return $this
     */
    public function setOther($var)
    {
        GPBUtil::checkMessage($var, \sl_eit_proto::class);
        $this->other = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto other_schedule = 4;</code>
     * @return \sl_eit_proto
     */
    public function getOtherSchedule()
    {
        return $this->other_schedule;
    }

    /**
     * Generated from protobuf field <code>.sl_eit_proto other_schedule = 4;</code>
     * @param \sl_eit_proto $var
     * @return $this
     */
    public function setOtherSchedule($var)
    {
        GPBUtil::checkMessage($var, \sl_eit_proto::class);
        $this->other_schedule = $var;

        return $this;
    }

}

