<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * descriptor_tag = 0x58 (88)
 *
 * Generated from protobuf message <code>sl_local_time_offset_proto</code>
 */
class sl_local_time_offset_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     */
    protected $country_code = '';
    /**
     * Generated from protobuf field <code>uint32 country_region_id = 2;</code>
     */
    protected $country_region_id = 0;
    /**
     * Generated from protobuf field <code>uint32 local_time_offset_polarity = 3;</code>
     */
    protected $local_time_offset_polarity = 0;
    /**
     * Generated from protobuf field <code>uint32 local_time_offset = 4;</code>
     */
    protected $local_time_offset = 0;
    /**
     * Generated from protobuf field <code>uint64 time_of_change = 5;</code>
     */
    protected $time_of_change = 0;
    /**
     * Generated from protobuf field <code>uint32 next_time_offset = 6;</code>
     */
    protected $next_time_offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $country_code
     *     @type int $country_region_id
     *     @type int $local_time_offset_polarity
     *     @type int $local_time_offset
     *     @type int|string $time_of_change
     *     @type int $next_time_offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * Generated from protobuf field <code>string country_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 country_region_id = 2;</code>
     * @return int
     */
    public function getCountryRegionId()
    {
        return $this->country_region_id;
    }

    /**
     * Generated from protobuf field <code>uint32 country_region_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryRegionId($var)
    {
        GPBUtil::checkUint32($var);
        $this->country_region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 local_time_offset_polarity = 3;</code>
     * @return int
     */
    public function getLocalTimeOffsetPolarity()
    {
        return $this->local_time_offset_polarity;
    }

    /**
     * Generated from protobuf field <code>uint32 local_time_offset_polarity = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLocalTimeOffsetPolarity($var)
    {
        GPBUtil::checkUint32($var);
        $this->local_time_offset_polarity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 local_time_offset = 4;</code>
     * @return int
     */
    public function getLocalTimeOffset()
    {
        return $this->local_time_offset;
    }

    /**
     * Generated from protobuf field <code>uint32 local_time_offset = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLocalTimeOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->local_time_offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 time_of_change = 5;</code>
     * @return int|string
     */
    public function getTimeOfChange()
    {
        return $this->time_of_change;
    }

    /**
     * Generated from protobuf field <code>uint64 time_of_change = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeOfChange($var)
    {
        GPBUtil::checkUint64($var);
        $this->time_of_change = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 next_time_offset = 6;</code>
     * @return int
     */
    public function getNextTimeOffset()
    {
        return $this->next_time_offset;
    }

    /**
     * Generated from protobuf field <code>uint32 next_time_offset = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setNextTimeOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->next_time_offset = $var;

        return $this;
    }

}

