<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;/////////////////////////////////////////////////////////////////////////////
 * Other_pid
 *
 * Generated from protobuf message <code>sl_other_pid_pids_proto</code>
 */
class sl_other_pid_pids_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<uint32, uint32> src_dst = 1;</code>
     */
    private $src_dst;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $src_dst
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<uint32, uint32> src_dst = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSrcDst()
    {
        return $this->src_dst;
    }

    /**
     * Generated from protobuf field <code>map<uint32, uint32> src_dst = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSrcDst($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->src_dst = $arr;

        return $this;
    }

}

