<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_pmts_model_proto</code>
 */
class sl_pmts_model_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .sl_pmt_model_proto pmts = 1;</code>
     */
    private $pmts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \sl_pmt_model_proto[]|\Google\Protobuf\Internal\RepeatedField $pmts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .sl_pmt_model_proto pmts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPmts()
    {
        return $this->pmts;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_pmt_model_proto pmts = 1;</code>
     * @param \sl_pmt_model_proto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPmts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_pmt_model_proto::class);
        $this->pmts = $arr;

        return $this;
    }

}

