<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

/**
 * Protobuf type <code>sl_stream_type_proto</code>
 */
class sl_stream_type_proto
{
    /**
     * Generated from protobuf enum <code>video_stream = 0;</code>
     */
    const video_stream = 0;
    /**
     * Generated from protobuf enum <code>audio_stream = 1;</code>
     */
    const audio_stream = 1;
    /**
     * Generated from protobuf enum <code>teletext_stream = 2;</code>
     */
    const teletext_stream = 2;
    /**
     * Generated from protobuf enum <code>subtuitle_stream = 3;</code>
     */
    const subtuitle_stream = 3;
    /**
     * Generated from protobuf enum <code>scte104_stream = 4;</code>
     */
    const scte104_stream = 4;
    /**
     * Generated from protobuf enum <code>scte35_stream = 5;</code>
     */
    const scte35_stream = 5;
    /**
     * Generated from protobuf enum <code>mpeg_ts_stream = 6;</code>
     */
    const mpeg_ts_stream = 6;
    /**
     * Generated from protobuf enum <code>unknown_stream = 255;</code>
     */
    const unknown_stream = 255;

    private static $valueToName = [
        self::video_stream => 'video_stream',
        self::audio_stream => 'audio_stream',
        self::teletext_stream => 'teletext_stream',
        self::subtuitle_stream => 'subtuitle_stream',
        self::scte104_stream => 'scte104_stream',
        self::scte35_stream => 'scte35_stream',
        self::mpeg_ts_stream => 'mpeg_ts_stream',
        self::unknown_stream => 'unknown_stream',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

