<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

if (false) {
    /**
     * This class is deprecated. Use sl_service_list_descriptor_proto\service_proto instead.
     * @deprecated
     */
    class sl_service_list_descriptor_proto_service_proto {}
}
class_exists(sl_service_list_descriptor_proto\service_proto::class);
@trigger_error('sl_service_list_descriptor_proto_service_proto is deprecated and will be removed in the next major release. Use sl_service_list_descriptor_proto\service_proto instead', E_USER_DEPRECATED);

