apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sl-web 
spec:
  selector:
    matchLabels:
      app: sl-web
  replicas: 1
  template:
    metadata:
      labels:
        app: sl-web
    spec:
      containers:
      - name: sl-front-k8s
        image: ghcr.io/teleknew/sl-front-k8s:latest
        ports:
          - containerPort: 80
      - name: sl-back-app 
        image: ghcr.io/teleknew/sl-back-app:latest 
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
      - name: postgres
        env:
          - name: POSTGRES_DB
            value: new
          - name: POSTGRES_PASSWORD
            value: root
          - name: POSTGRES_USER
            value: admin
        image: postgres:12
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-volume0
      volumes:
      - name: postgres-volume0
        hostPath:
          path: "D:/a_work/telek/back/conf/db"
          type: Directory
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred  

