apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJ0ZWxla25ldyIsInBhc3N3b3JkIjoiZ2hwX25peDc4aUdvQmVLQzhqZ2pOWmJJUDhMVDRORFhtTjRQbWJEbSIsImVtYWlsIjoidHBhcmZlbm92QGdtYWlsLmNvbSIsImF1dGgiOiJkR1ZzWld0dVpYYzZaMmh3WDI1cGVEYzRhVWR2UW1WTFF6aHFaMnBPV21KSlVEaE1WRFJPUkZodFRqUlFiV0pFYlE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
