<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EIT
 *
 * Generated from protobuf message <code>sl_event_info_proto</code>
 */
class sl_event_info_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 event_id = 1;</code>
     */
    protected $event_id = 0;
    /**
     * Generated from protobuf field <code>uint64 start_time = 2;</code>
     */
    protected $start_time = 0;
    /**
     * Generated from protobuf field <code>uint32 duration = 3;</code>
     */
    protected $duration = 0;
    /**
     * Generated from protobuf field <code>uint32 running_status = 4;</code>
     */
    protected $running_status = 0;
    /**
     * Generated from protobuf field <code>uint32 free_CA_mode = 5;</code>
     */
    protected $free_CA_mode = 0;
    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 6;</code>
     */
    private $descriptors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $event_id
     *     @type int|string $start_time
     *     @type int $duration
     *     @type int $running_status
     *     @type int $free_CA_mode
     *     @type \sl_descriptor_proto[]|\Google\Protobuf\Internal\RepeatedField $descriptors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 event_id = 1;</code>
     * @return int
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * Generated from protobuf field <code>uint32 event_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkUint32($var);
        $this->event_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_time = 2;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>uint64 start_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 3;</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 running_status = 4;</code>
     * @return int
     */
    public function getRunningStatus()
    {
        return $this->running_status;
    }

    /**
     * Generated from protobuf field <code>uint32 running_status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRunningStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->running_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 free_CA_mode = 5;</code>
     * @return int
     */
    public function getFreeCAMode()
    {
        return $this->free_CA_mode;
    }

    /**
     * Generated from protobuf field <code>uint32 free_CA_mode = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFreeCAMode($var)
    {
        GPBUtil::checkUint32($var);
        $this->free_CA_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDescriptors()
    {
        return $this->descriptors;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 6;</code>
     * @param \sl_descriptor_proto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDescriptors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_descriptor_proto::class);
        $this->descriptors = $arr;

        return $this;
    }

}

