<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_eit_model_proto</code>
 */
class sl_eit_model_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl_table_state_proto state = 1;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>uint64 max_bitrate = 3;</code>
     */
    protected $max_bitrate = 0;
    /**
     * Generated from protobuf field <code>uint64 actual_repetition = 4;</code>
     */
    protected $actual_repetition = 0;
    /**
     * Generated from protobuf field <code>uint64 other_repetition = 5;</code>
     */
    protected $other_repetition = 0;
    /**
     * Generated from protobuf field <code>uint64 actual_schedule_repetition = 6;</code>
     */
    protected $actual_schedule_repetition = 0;
    /**
     * Generated from protobuf field <code>uint64 other_schedule_repetition = 7;</code>
     */
    protected $other_schedule_repetition = 0;
    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual = 8;</code>
     */
    private $actual;
    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other = 9;</code>
     */
    private $other;
    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual_schedule = 10;</code>
     */
    private $actual_schedule;
    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other_schedule = 11;</code>
     */
    private $other_schedule;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type string $path
     *     @type int|string $max_bitrate
     *     @type int|string $actual_repetition
     *     @type int|string $other_repetition
     *     @type int|string $actual_schedule_repetition
     *     @type int|string $other_schedule_repetition
     *     @type array|\Google\Protobuf\Internal\MapField $actual
     *     @type array|\Google\Protobuf\Internal\MapField $other
     *     @type array|\Google\Protobuf\Internal\MapField $actual_schedule
     *     @type array|\Google\Protobuf\Internal\MapField $other_schedule
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl_table_state_proto state = 1;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.sl_table_state_proto state = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \sl_table_state_proto::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max_bitrate = 3;</code>
     * @return int|string
     */
    public function getMaxBitrate()
    {
        return $this->max_bitrate;
    }

    /**
     * Generated from protobuf field <code>uint64 max_bitrate = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxBitrate($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_bitrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 actual_repetition = 4;</code>
     * @return int|string
     */
    public function getActualRepetition()
    {
        return $this->actual_repetition;
    }

    /**
     * Generated from protobuf field <code>uint64 actual_repetition = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActualRepetition($var)
    {
        GPBUtil::checkUint64($var);
        $this->actual_repetition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 other_repetition = 5;</code>
     * @return int|string
     */
    public function getOtherRepetition()
    {
        return $this->other_repetition;
    }

    /**
     * Generated from protobuf field <code>uint64 other_repetition = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOtherRepetition($var)
    {
        GPBUtil::checkUint64($var);
        $this->other_repetition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 actual_schedule_repetition = 6;</code>
     * @return int|string
     */
    public function getActualScheduleRepetition()
    {
        return $this->actual_schedule_repetition;
    }

    /**
     * Generated from protobuf field <code>uint64 actual_schedule_repetition = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActualScheduleRepetition($var)
    {
        GPBUtil::checkUint64($var);
        $this->actual_schedule_repetition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 other_schedule_repetition = 7;</code>
     * @return int|string
     */
    public function getOtherScheduleRepetition()
    {
        return $this->other_schedule_repetition;
    }

    /**
     * Generated from protobuf field <code>uint64 other_schedule_repetition = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOtherScheduleRepetition($var)
    {
        GPBUtil::checkUint64($var);
        $this->other_schedule_repetition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActual($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_eit_service_model_proto::class);
        $this->actual = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOther()
    {
        return $this->other;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOther($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_eit_service_model_proto::class);
        $this->other = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual_schedule = 10;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActualSchedule()
    {
        return $this->actual_schedule;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> actual_schedule = 10;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActualSchedule($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_eit_service_model_proto::class);
        $this->actual_schedule = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other_schedule = 11;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOtherSchedule()
    {
        return $this->other_schedule;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_eit_service_model_proto> other_schedule = 11;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOtherSchedule($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_eit_service_model_proto::class);
        $this->other_schedule = $arr;

        return $this;
    }

}

