<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

if (false) {
    /**
     * This class is deprecated. Use sl_ll_device_info_proto\sl_ll_device_type_proto instead.
     * @deprecated
     */
    class sl_ll_device_info_proto_sl_ll_device_type_proto {}
}
class_exists(sl_ll_device_info_proto\sl_ll_device_type_proto::class);
@trigger_error('sl_ll_device_info_proto_sl_ll_device_type_proto is deprecated and will be removed in the next major release. Use sl_ll_device_info_proto\sl_ll_device_type_proto instead', E_USER_DEPRECATED);

