<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * descriptor_tag = 0x55 (85)
 *
 * Generated from protobuf message <code>sl_parental_rating_descriptor_proto</code>
 */
class sl_parental_rating_descriptor_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     */
    protected $descriptor_tag = 0;
    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     */
    protected $descriptor_length = 0;
    /**
     * Generated from protobuf field <code>repeated .sl_parental_rating_descriptor_proto.rating ratings = 3;</code>
     */
    private $ratings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $descriptor_tag
     *     @type int $descriptor_length
     *     @type \sl_parental_rating_descriptor_proto\rating[]|\Google\Protobuf\Internal\RepeatedField $ratings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @return int
     */
    public function getDescriptorTag()
    {
        return $this->descriptor_tag;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorTag($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @return int
     */
    public function getDescriptorLength()
    {
        return $this->descriptor_length;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_parental_rating_descriptor_proto.rating ratings = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRatings()
    {
        return $this->ratings;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_parental_rating_descriptor_proto.rating ratings = 3;</code>
     * @param \sl_parental_rating_descriptor_proto\rating[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRatings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_parental_rating_descriptor_proto\rating::class);
        $this->ratings = $arr;

        return $this;
    }

}

