<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_sdt_model_proto</code>
 */
class sl_sdt_model_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> actual = 1;</code>
     */
    private $actual;
    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> other = 2;</code>
     */
    private $other;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $actual
     *     @type array|\Google\Protobuf\Internal\MapField $other
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> actual = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> actual = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActual($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_sdts_sds_model::class);
        $this->actual = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> other = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOther()
    {
        return $this->other;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_sdts_sds_model> other = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOther($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_sdts_sds_model::class);
        $this->other = $arr;

        return $this;
    }

}

