<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_descriptor_proto</code>
 */
class sl_descriptor_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     */
    protected $descriptor_tag = 0;
    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     */
    protected $descriptor_length = 0;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $descriptor_tag
     *     @type int $descriptor_length
     *     @type \sl_unknown_descriptor_proto $unknown_descriptor
     *     @type \sl_service_descriptor_proto $service_descriptor
     *     @type \sl_network_name_descriptor_proto $network_name_descriptor
     *     @type \sl_stream_identifier_descriptor_proto $stream_identifier_descriptor
     *     @type \sl_teletext_descriptor_proto $teletext_descriptor
     *     @type \sl_local_time_offset_descriptor_proto $local_time_offset_descriptor
     *     @type \sl_short_event_descriptor_proto $short_event_descriptor
     *     @type \sl_extended_event_descriptor_proto $extended_event_descriptor
     *     @type \sl_parental_rating_descriptor_proto $parental_rating_descriptor
     *     @type \sl_service_list_descriptor_proto $service_list_descriptor
     *     @type \sl_logical_channel_description_proto $logical_channel_descriptor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @return int
     */
    public function getDescriptorTag()
    {
        return $this->descriptor_tag;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorTag($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @return int
     */
    public function getDescriptorLength()
    {
        return $this->descriptor_length;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_unknown_descriptor_proto unknown_descriptor = 3;</code>
     * @return \sl_unknown_descriptor_proto
     */
    public function getUnknownDescriptor()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.sl_unknown_descriptor_proto unknown_descriptor = 3;</code>
     * @param \sl_unknown_descriptor_proto $var
     * @return $this
     */
    public function setUnknownDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_unknown_descriptor_proto::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_service_descriptor_proto service_descriptor = 4;</code>
     * @return \sl_service_descriptor_proto
     */
    public function getServiceDescriptor()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.sl_service_descriptor_proto service_descriptor = 4;</code>
     * @param \sl_service_descriptor_proto $var
     * @return $this
     */
    public function setServiceDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_service_descriptor_proto::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_network_name_descriptor_proto network_name_descriptor = 5;</code>
     * @return \sl_network_name_descriptor_proto
     */
    public function getNetworkNameDescriptor()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.sl_network_name_descriptor_proto network_name_descriptor = 5;</code>
     * @param \sl_network_name_descriptor_proto $var
     * @return $this
     */
    public function setNetworkNameDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_network_name_descriptor_proto::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_stream_identifier_descriptor_proto stream_identifier_descriptor = 6;</code>
     * @return \sl_stream_identifier_descriptor_proto
     */
    public function getStreamIdentifierDescriptor()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.sl_stream_identifier_descriptor_proto stream_identifier_descriptor = 6;</code>
     * @param \sl_stream_identifier_descriptor_proto $var
     * @return $this
     */
    public function setStreamIdentifierDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_stream_identifier_descriptor_proto::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_teletext_descriptor_proto teletext_descriptor = 7;</code>
     * @return \sl_teletext_descriptor_proto
     */
    public function getTeletextDescriptor()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.sl_teletext_descriptor_proto teletext_descriptor = 7;</code>
     * @param \sl_teletext_descriptor_proto $var
     * @return $this
     */
    public function setTeletextDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_teletext_descriptor_proto::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_local_time_offset_descriptor_proto local_time_offset_descriptor = 8;</code>
     * @return \sl_local_time_offset_descriptor_proto
     */
    public function getLocalTimeOffsetDescriptor()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.sl_local_time_offset_descriptor_proto local_time_offset_descriptor = 8;</code>
     * @param \sl_local_time_offset_descriptor_proto $var
     * @return $this
     */
    public function setLocalTimeOffsetDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_local_time_offset_descriptor_proto::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_short_event_descriptor_proto short_event_descriptor = 9;</code>
     * @return \sl_short_event_descriptor_proto
     */
    public function getShortEventDescriptor()
    {
        return $this->readOneof(9);
    }

    /**
     * Generated from protobuf field <code>.sl_short_event_descriptor_proto short_event_descriptor = 9;</code>
     * @param \sl_short_event_descriptor_proto $var
     * @return $this
     */
    public function setShortEventDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_short_event_descriptor_proto::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_extended_event_descriptor_proto extended_event_descriptor = 10;</code>
     * @return \sl_extended_event_descriptor_proto
     */
    public function getExtendedEventDescriptor()
    {
        return $this->readOneof(10);
    }

    /**
     * Generated from protobuf field <code>.sl_extended_event_descriptor_proto extended_event_descriptor = 10;</code>
     * @param \sl_extended_event_descriptor_proto $var
     * @return $this
     */
    public function setExtendedEventDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_extended_event_descriptor_proto::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_parental_rating_descriptor_proto parental_rating_descriptor = 11;</code>
     * @return \sl_parental_rating_descriptor_proto
     */
    public function getParentalRatingDescriptor()
    {
        return $this->readOneof(11);
    }

    /**
     * Generated from protobuf field <code>.sl_parental_rating_descriptor_proto parental_rating_descriptor = 11;</code>
     * @param \sl_parental_rating_descriptor_proto $var
     * @return $this
     */
    public function setParentalRatingDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_parental_rating_descriptor_proto::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_service_list_descriptor_proto service_list_descriptor = 12;</code>
     * @return \sl_service_list_descriptor_proto
     */
    public function getServiceListDescriptor()
    {
        return $this->readOneof(12);
    }

    /**
     * Generated from protobuf field <code>.sl_service_list_descriptor_proto service_list_descriptor = 12;</code>
     * @param \sl_service_list_descriptor_proto $var
     * @return $this
     */
    public function setServiceListDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_service_list_descriptor_proto::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_logical_channel_description_proto logical_channel_descriptor = 13;</code>
     * @return \sl_logical_channel_description_proto
     */
    public function getLogicalChannelDescriptor()
    {
        return $this->readOneof(13);
    }

    /**
     * Generated from protobuf field <code>.sl_logical_channel_description_proto logical_channel_descriptor = 13;</code>
     * @param \sl_logical_channel_description_proto $var
     * @return $this
     */
    public function setLogicalChannelDescriptor($var)
    {
        GPBUtil::checkMessage($var, \sl_logical_channel_description_proto::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

