<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

if (false) {
    /**
     * This class is deprecated. Use sl_extended_event_descriptor_proto\item instead.
     * @deprecated
     */
    class sl_extended_event_descriptor_proto_item {}
}
class_exists(sl_extended_event_descriptor_proto\item::class);
@trigger_error('sl_extended_event_descriptor_proto_item is deprecated and will be removed in the next major release. Use sl_extended_event_descriptor_proto\item instead', E_USER_DEPRECATED);

