<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_graph_input_program_proto</code>
 */
class sl_graph_input_program_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl_graph_proto graph = 1;</code>
     */
    protected $graph = null;
    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 2;</code>
     */
    protected $input_program = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \sl_graph_proto $graph
     *     @type \sl_input_program_proto $input_program
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl_graph_proto graph = 1;</code>
     * @return \sl_graph_proto
     */
    public function getGraph()
    {
        return $this->graph;
    }

    /**
     * Generated from protobuf field <code>.sl_graph_proto graph = 1;</code>
     * @param \sl_graph_proto $var
     * @return $this
     */
    public function setGraph($var)
    {
        GPBUtil::checkMessage($var, \sl_graph_proto::class);
        $this->graph = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 2;</code>
     * @return \sl_input_program_proto
     */
    public function getInputProgram()
    {
        return $this->input_program;
    }

    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 2;</code>
     * @param \sl_input_program_proto $var
     * @return $this
     */
    public function setInputProgram($var)
    {
        GPBUtil::checkMessage($var, \sl_input_program_proto::class);
        $this->input_program = $var;

        return $this;
    }

}

