<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;/////////////////////////////////////////////////////////////////////////////
 *
 * Generated from protobuf message <code>sl_input_info_proto</code>
 */
class sl_input_info_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl_input_pat_proto pat = 1;</code>
     */
    protected $pat = null;
    /**
     * Generated from protobuf field <code>.sl_cat_proto cat = 2;</code>
     */
    protected $cat = null;
    /**
     * Generated from protobuf field <code>.sl_tot_proto tot = 3;</code>
     */
    protected $tot = null;
    /**
     * Generated from protobuf field <code>.sl_tdt_proto tdt = 4;</code>
     */
    protected $tdt = null;
    /**
     * Generated from protobuf field <code>.sl_input_sdt_proto sdt = 5;</code>
     */
    protected $sdt = null;
    /**
     * Generated from protobuf field <code>.sl_input_nit_proto nit = 7;</code>
     */
    protected $nit = null;
    /**
     * Generated from protobuf field <code>.sl_input_eit_proto eit = 8;</code>
     */
    protected $eit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \sl_input_pat_proto $pat
     *     @type \sl_cat_proto $cat
     *     @type \sl_tot_proto $tot
     *     @type \sl_tdt_proto $tdt
     *     @type \sl_input_sdt_proto $sdt
     *     @type \sl_input_nit_proto $nit
     *     @type \sl_input_eit_proto $eit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl_input_pat_proto pat = 1;</code>
     * @return \sl_input_pat_proto
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * Generated from protobuf field <code>.sl_input_pat_proto pat = 1;</code>
     * @param \sl_input_pat_proto $var
     * @return $this
     */
    public function setPat($var)
    {
        GPBUtil::checkMessage($var, \sl_input_pat_proto::class);
        $this->pat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_cat_proto cat = 2;</code>
     * @return \sl_cat_proto
     */
    public function getCat()
    {
        return $this->cat;
    }

    /**
     * Generated from protobuf field <code>.sl_cat_proto cat = 2;</code>
     * @param \sl_cat_proto $var
     * @return $this
     */
    public function setCat($var)
    {
        GPBUtil::checkMessage($var, \sl_cat_proto::class);
        $this->cat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_tot_proto tot = 3;</code>
     * @return \sl_tot_proto
     */
    public function getTot()
    {
        return $this->tot;
    }

    /**
     * Generated from protobuf field <code>.sl_tot_proto tot = 3;</code>
     * @param \sl_tot_proto $var
     * @return $this
     */
    public function setTot($var)
    {
        GPBUtil::checkMessage($var, \sl_tot_proto::class);
        $this->tot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_tdt_proto tdt = 4;</code>
     * @return \sl_tdt_proto
     */
    public function getTdt()
    {
        return $this->tdt;
    }

    /**
     * Generated from protobuf field <code>.sl_tdt_proto tdt = 4;</code>
     * @param \sl_tdt_proto $var
     * @return $this
     */
    public function setTdt($var)
    {
        GPBUtil::checkMessage($var, \sl_tdt_proto::class);
        $this->tdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_input_sdt_proto sdt = 5;</code>
     * @return \sl_input_sdt_proto
     */
    public function getSdt()
    {
        return $this->sdt;
    }

    /**
     * Generated from protobuf field <code>.sl_input_sdt_proto sdt = 5;</code>
     * @param \sl_input_sdt_proto $var
     * @return $this
     */
    public function setSdt($var)
    {
        GPBUtil::checkMessage($var, \sl_input_sdt_proto::class);
        $this->sdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_input_nit_proto nit = 7;</code>
     * @return \sl_input_nit_proto
     */
    public function getNit()
    {
        return $this->nit;
    }

    /**
     * Generated from protobuf field <code>.sl_input_nit_proto nit = 7;</code>
     * @param \sl_input_nit_proto $var
     * @return $this
     */
    public function setNit($var)
    {
        GPBUtil::checkMessage($var, \sl_input_nit_proto::class);
        $this->nit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_input_eit_proto eit = 8;</code>
     * @return \sl_input_eit_proto
     */
    public function getEit()
    {
        return $this->eit;
    }

    /**
     * Generated from protobuf field <code>.sl_input_eit_proto eit = 8;</code>
     * @param \sl_input_eit_proto $var
     * @return $this
     */
    public function setEit($var)
    {
        GPBUtil::checkMessage($var, \sl_input_eit_proto::class);
        $this->eit = $var;

        return $this;
    }

}

