<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_instance.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_input_program_encoder_proto</code>
 */
class sl_input_program_encoder_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 1;</code>
     */
    protected $input_program = null;
    /**
     * Generated from protobuf field <code>.sl_encoder_proto encoder = 2;</code>
     */
    protected $encoder = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \sl_input_program_proto $input_program
     *     @type \sl_encoder_proto $encoder
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphInstance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 1;</code>
     * @return \sl_input_program_proto
     */
    public function getInputProgram()
    {
        return $this->input_program;
    }

    /**
     * Generated from protobuf field <code>.sl_input_program_proto input_program = 1;</code>
     * @param \sl_input_program_proto $var
     * @return $this
     */
    public function setInputProgram($var)
    {
        GPBUtil::checkMessage($var, \sl_input_program_proto::class);
        $this->input_program = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl_encoder_proto encoder = 2;</code>
     * @return \sl_encoder_proto
     */
    public function getEncoder()
    {
        return $this->encoder;
    }

    /**
     * Generated from protobuf field <code>.sl_encoder_proto encoder = 2;</code>
     * @param \sl_encoder_proto $var
     * @return $this
     */
    public function setEncoder($var)
    {
        GPBUtil::checkMessage($var, \sl_encoder_proto::class);
        $this->encoder = $var;

        return $this;
    }

}

