<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

if (false) {
    /**
     * This class is deprecated. Use sl_logical_channel_description_proto\logical_channel_proto instead.
     * @deprecated
     */
    class sl_logical_channel_description_proto_logical_channel_proto {}
}
class_exists(sl_logical_channel_description_proto\logical_channel_proto::class);
@trigger_error('sl_logical_channel_description_proto_logical_channel_proto is deprecated and will be removed in the next major release. Use sl_logical_channel_description_proto\logical_channel_proto instead', E_USER_DEPRECATED);

