<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_other_pid_proto</code>
 */
class sl_other_pid_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .sl_other_pid_pids_proto> input = 1;</code>
     */
    private $input;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $input
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_other_pid_pids_proto> input = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>map<string, .sl_other_pid_pids_proto> input = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_other_pid_pids_proto::class);
        $this->input = $arr;

        return $this;
    }

}

