<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_parsing_state_proto</code>
 */
class sl_parsing_state_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_parsing = 1;</code>
     */
    protected $is_parsing = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_parsing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_parsing = 1;</code>
     * @return bool
     */
    public function getIsParsing()
    {
        return $this->is_parsing;
    }

    /**
     * Generated from protobuf field <code>bool is_parsing = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsParsing($var)
    {
        GPBUtil::checkBool($var);
        $this->is_parsing = $var;

        return $this;
    }

}

