<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_pair_model</code>
 */
class sl_pair_model extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 first = 1;</code>
     */
    protected $first = 0;
    /**
     * Generated from protobuf field <code>uint32 second = 2;</code>
     */
    protected $second = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $first
     *     @type int $second
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 first = 1;</code>
     * @return int
     */
    public function getFirst()
    {
        return $this->first;
    }

    /**
     * Generated from protobuf field <code>uint32 first = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFirst($var)
    {
        GPBUtil::checkUint32($var);
        $this->first = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 second = 2;</code>
     * @return int
     */
    public function getSecond()
    {
        return $this->second;
    }

    /**
     * Generated from protobuf field <code>uint32 second = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSecond($var)
    {
        GPBUtil::checkUint32($var);
        $this->second = $var;

        return $this;
    }

}

