<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

if (false) {
    /**
     * This class is deprecated. Use sl_parental_rating_descriptor_proto\rating instead.
     * @deprecated
     */
    class sl_parental_rating_descriptor_proto_rating {}
}
class_exists(sl_parental_rating_descriptor_proto\rating::class);
@trigger_error('sl_parental_rating_descriptor_proto_rating is deprecated and will be removed in the next major release. Use sl_parental_rating_descriptor_proto\rating instead', E_USER_DEPRECATED);

