<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

if (false) {
    /**
     * This class is deprecated. Use sl_reserve_proto\sl_state_proto instead.
     * @deprecated
     */
    class sl_reserve_proto_sl_state_proto {}
}
class_exists(sl_reserve_proto\sl_state_proto::class);
@trigger_error('sl_reserve_proto_sl_state_proto is deprecated and will be removed in the next major release. Use sl_reserve_proto\sl_state_proto instead', E_USER_DEPRECATED);

