<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * descriptor_tag = 0x48 (72)
 *
 * Generated from protobuf message <code>sl_service_descriptor_proto</code>
 */
class sl_service_descriptor_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     */
    protected $descriptor_tag = 0;
    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     */
    protected $descriptor_length = 0;
    /**
     * Generated from protobuf field <code>uint32 service_type = 3;</code>
     */
    protected $service_type = 0;
    /**
     * Generated from protobuf field <code>string service_provider_name = 4;</code>
     */
    protected $service_provider_name = '';
    /**
     * Generated from protobuf field <code>string service_name = 5;</code>
     */
    protected $service_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $descriptor_tag
     *     @type int $descriptor_length
     *     @type int $service_type
     *     @type string $service_provider_name
     *     @type string $service_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @return int
     */
    public function getDescriptorTag()
    {
        return $this->descriptor_tag;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_tag = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorTag($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @return int
     */
    public function getDescriptorLength()
    {
        return $this->descriptor_length;
    }

    /**
     * Generated from protobuf field <code>uint32 descriptor_length = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriptorLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->descriptor_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 service_type = 3;</code>
     * @return int
     */
    public function getServiceType()
    {
        return $this->service_type;
    }

    /**
     * Generated from protobuf field <code>uint32 service_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceType($var)
    {
        GPBUtil::checkUint32($var);
        $this->service_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_provider_name = 4;</code>
     * @return string
     */
    public function getServiceProviderName()
    {
        return $this->service_provider_name;
    }

    /**
     * Generated from protobuf field <code>string service_provider_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceProviderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_provider_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 5;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

}

