<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_stream_map_proto</code>
 */
class sl_stream_map_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 stream_type = 1;</code>
     */
    protected $stream_type = 0;
    /**
     * Generated from protobuf field <code>uint32 elementary_PID = 2;</code>
     */
    protected $elementary_PID = 0;
    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 3;</code>
     */
    private $descriptors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stream_type
     *     @type int $elementary_PID
     *     @type \sl_descriptor_proto[]|\Google\Protobuf\Internal\RepeatedField $descriptors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 stream_type = 1;</code>
     * @return int
     */
    public function getStreamType()
    {
        return $this->stream_type;
    }

    /**
     * Generated from protobuf field <code>uint32 stream_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStreamType($var)
    {
        GPBUtil::checkUint32($var);
        $this->stream_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 elementary_PID = 2;</code>
     * @return int
     */
    public function getElementaryPID()
    {
        return $this->elementary_PID;
    }

    /**
     * Generated from protobuf field <code>uint32 elementary_PID = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setElementaryPID($var)
    {
        GPBUtil::checkUint32($var);
        $this->elementary_PID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDescriptors()
    {
        return $this->descriptors;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_descriptor_proto descriptors = 3;</code>
     * @param \sl_descriptor_proto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDescriptors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_descriptor_proto::class);
        $this->descriptors = $arr;

        return $this;
    }

}

