<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl_sdt_proto</code>
 */
class sl_sdt_proto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     */
    protected $version_number = 0;
    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     */
    protected $transport_stream_id = 0;
    /**
     * Generated from protobuf field <code>uint32 original_network_id = 3;</code>
     */
    protected $original_network_id = 0;
    /**
     * Generated from protobuf field <code>repeated .sl_sdt_service_proto sds = 4;</code>
     */
    private $sds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version_number
     *     @type int $transport_stream_id
     *     @type int $original_network_id
     *     @type \sl_sdt_service_proto[]|\Google\Protobuf\Internal\RepeatedField $sds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @return int
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     * @return int
     */
    public function getTransportStreamId()
    {
        return $this->transport_stream_id;
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTransportStreamId($var)
    {
        GPBUtil::checkUint32($var);
        $this->transport_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 original_network_id = 3;</code>
     * @return int
     */
    public function getOriginalNetworkId()
    {
        return $this->original_network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 original_network_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginalNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->original_network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_sdt_service_proto sds = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSds()
    {
        return $this->sds;
    }

    /**
     * Generated from protobuf field <code>repeated .sl_sdt_service_proto sds = 4;</code>
     * @param \sl_sdt_service_proto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \sl_sdt_service_proto::class);
        $this->sds = $arr;

        return $this;
    }

}

