<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

/**
 * Protobuf type <code>sl_video_encoder_type_proto</code>
 */
class sl_video_encoder_type_proto
{
    /**
     * Generated from protobuf enum <code>sl_mc_mpeg_encoder = 0;</code>
     */
    const sl_mc_mpeg_encoder = 0;
    /**
     * Generated from protobuf enum <code>sl_intel_mpeg_encoder = 1;</code>
     */
    const sl_intel_mpeg_encoder = 1;
    /**
     * Generated from protobuf enum <code>sl_mc_avc_encoder = 2;</code>
     */
    const sl_mc_avc_encoder = 2;
    /**
     * Generated from protobuf enum <code>sl_intel_avc_encoder = 3;</code>
     */
    const sl_intel_avc_encoder = 3;
    /**
     * Generated from protobuf enum <code>sl_nvidia_avc_encoder = 4;</code>
     */
    const sl_nvidia_avc_encoder = 4;
    /**
     * Generated from protobuf enum <code>sl_mc_hevc_encoder = 5;</code>
     */
    const sl_mc_hevc_encoder = 5;
    /**
     * Generated from protobuf enum <code>sl_intel_hevc_encoder = 6;</code>
     */
    const sl_intel_hevc_encoder = 6;
    /**
     * Generated from protobuf enum <code>sl_nvidia_hevc_encoder = 7;</code>
     */
    const sl_nvidia_hevc_encoder = 7;

    private static $valueToName = [
        self::sl_mc_mpeg_encoder => 'sl_mc_mpeg_encoder',
        self::sl_intel_mpeg_encoder => 'sl_intel_mpeg_encoder',
        self::sl_mc_avc_encoder => 'sl_mc_avc_encoder',
        self::sl_intel_avc_encoder => 'sl_intel_avc_encoder',
        self::sl_nvidia_avc_encoder => 'sl_nvidia_avc_encoder',
        self::sl_mc_hevc_encoder => 'sl_mc_hevc_encoder',
        self::sl_intel_hevc_encoder => 'sl_intel_hevc_encoder',
        self::sl_nvidia_hevc_encoder => 'sl_nvidia_hevc_encoder',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

