version: '3'
services:

  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ../../conf/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=new
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin