<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLAffinityMaskProto</code>
 */
class SLAffinityMaskProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bool affinity = 1;</code>
     */
    private $affinity;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool[]|\Google\Protobuf\Internal\RepeatedField $affinity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bool affinity = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAffinity()
    {
        return $this->affinity;
    }

    /**
     * Generated from protobuf field <code>repeated bool affinity = 1;</code>
     * @param bool[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAffinity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->affinity = $arr;

        return $this;
    }

}

