<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLDeviceProto\SLDeviceTypeProto instead.
     * @deprecated
     */
    class SLDeviceProto_SLDeviceTypeProto {}
}
class_exists(SLDeviceProto\SLDeviceTypeProto::class);
@trigger_error('Sl\SLDeviceProto_SLDeviceTypeProto is deprecated and will be removed in the next major release. Use Sl\SLDeviceProto\SLDeviceTypeProto instead', E_USER_DEPRECATED);

