<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLEncoderSupportProto</code>
 */
class SLEncoderSupportProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .sl.SLVideoEncoderTypeProto video = 1;</code>
     */
    private $video;
    /**
     * Generated from protobuf field <code>repeated .sl.SLAudioEncoderTypeProto audio = 2;</code>
     */
    private $audio;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $video
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $audio
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLVideoEncoderTypeProto video = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLVideoEncoderTypeProto video = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Sl\SLVideoEncoderTypeProto::class);
        $this->video = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLAudioEncoderTypeProto audio = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudio()
    {
        return $this->audio;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLAudioEncoderTypeProto audio = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudio($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Sl\SLAudioEncoderTypeProto::class);
        $this->audio = $arr;

        return $this;
    }

}

