<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLExtendedEventDescriptorProto\ItemProto instead.
     * @deprecated
     */
    class SLExtendedEventDescriptorProto_ItemProto {}
}
class_exists(SLExtendedEventDescriptorProto\ItemProto::class);
@trigger_error('Sl\SLExtendedEventDescriptorProto_ItemProto is deprecated and will be removed in the next major release. Use Sl\SLExtendedEventDescriptorProto\ItemProto instead', E_USER_DEPRECATED);

