<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLGraphOutputProgramProto</code>
 */
class SLGraphOutputProgramProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl.SLGraphProto graph = 1;</code>
     */
    protected $graph = null;
    /**
     * Generated from protobuf field <code>.sl.SLOutputProgramProto output_program = 2;</code>
     */
    protected $output_program = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLGraphProto $graph
     *     @type \Sl\SLOutputProgramProto $output_program
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl.SLGraphProto graph = 1;</code>
     * @return \Sl\SLGraphProto
     */
    public function getGraph()
    {
        return $this->graph;
    }

    /**
     * Generated from protobuf field <code>.sl.SLGraphProto graph = 1;</code>
     * @param \Sl\SLGraphProto $var
     * @return $this
     */
    public function setGraph($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLGraphProto::class);
        $this->graph = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLOutputProgramProto output_program = 2;</code>
     * @return \Sl\SLOutputProgramProto
     */
    public function getOutputProgram()
    {
        return $this->output_program;
    }

    /**
     * Generated from protobuf field <code>.sl.SLOutputProgramProto output_program = 2;</code>
     * @param \Sl\SLOutputProgramProto $var
     * @return $this
     */
    public function setOutputProgram($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLOutputProgramProto::class);
        $this->output_program = $var;

        return $this;
    }

}

