<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;/////////////////////////////////////////////////////////////////////////////
 *
 * Generated from protobuf message <code>sl.SLInputInfoProto</code>
 */
class SLInputInfoProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl.SLInputPatProto pat = 1;</code>
     */
    protected $pat = null;
    /**
     * Generated from protobuf field <code>.sl.SLCatProto cat = 2;</code>
     */
    protected $cat = null;
    /**
     * Generated from protobuf field <code>.sl.SLTotProto tot = 3;</code>
     */
    protected $tot = null;
    /**
     * Generated from protobuf field <code>.sl.SLTdtProto tdt = 4;</code>
     */
    protected $tdt = null;
    /**
     * Generated from protobuf field <code>.sl.SLInputSdtProto sdt = 5;</code>
     */
    protected $sdt = null;
    /**
     * Generated from protobuf field <code>.sl.SLInputNitProto nit = 7;</code>
     */
    protected $nit = null;
    /**
     * Generated from protobuf field <code>.sl.SLInputEitProto eit = 8;</code>
     */
    protected $eit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLInputPatProto $pat
     *     @type \Sl\SLCatProto $cat
     *     @type \Sl\SLTotProto $tot
     *     @type \Sl\SLTdtProto $tdt
     *     @type \Sl\SLInputSdtProto $sdt
     *     @type \Sl\SLInputNitProto $nit
     *     @type \Sl\SLInputEitProto $eit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputPatProto pat = 1;</code>
     * @return \Sl\SLInputPatProto
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputPatProto pat = 1;</code>
     * @param \Sl\SLInputPatProto $var
     * @return $this
     */
    public function setPat($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLInputPatProto::class);
        $this->pat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLCatProto cat = 2;</code>
     * @return \Sl\SLCatProto
     */
    public function getCat()
    {
        return $this->cat;
    }

    /**
     * Generated from protobuf field <code>.sl.SLCatProto cat = 2;</code>
     * @param \Sl\SLCatProto $var
     * @return $this
     */
    public function setCat($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLCatProto::class);
        $this->cat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTotProto tot = 3;</code>
     * @return \Sl\SLTotProto
     */
    public function getTot()
    {
        return $this->tot;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTotProto tot = 3;</code>
     * @param \Sl\SLTotProto $var
     * @return $this
     */
    public function setTot($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLTotProto::class);
        $this->tot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTdtProto tdt = 4;</code>
     * @return \Sl\SLTdtProto
     */
    public function getTdt()
    {
        return $this->tdt;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTdtProto tdt = 4;</code>
     * @param \Sl\SLTdtProto $var
     * @return $this
     */
    public function setTdt($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLTdtProto::class);
        $this->tdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputSdtProto sdt = 5;</code>
     * @return \Sl\SLInputSdtProto
     */
    public function getSdt()
    {
        return $this->sdt;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputSdtProto sdt = 5;</code>
     * @param \Sl\SLInputSdtProto $var
     * @return $this
     */
    public function setSdt($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLInputSdtProto::class);
        $this->sdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputNitProto nit = 7;</code>
     * @return \Sl\SLInputNitProto
     */
    public function getNit()
    {
        return $this->nit;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputNitProto nit = 7;</code>
     * @param \Sl\SLInputNitProto $var
     * @return $this
     */
    public function setNit($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLInputNitProto::class);
        $this->nit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputEitProto eit = 8;</code>
     * @return \Sl\SLInputEitProto
     */
    public function getEit()
    {
        return $this->eit;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputEitProto eit = 8;</code>
     * @param \Sl\SLInputEitProto $var
     * @return $this
     */
    public function setEit($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLInputEitProto::class);
        $this->eit = $var;

        return $this;
    }

}

