<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLInputPatProto</code>
 */
class SLInputPatProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl.SLPatProto pat = 1;</code>
     */
    protected $pat = null;
    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtProto pmt = 2;</code>
     */
    private $pmt;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLPatProto $pat
     *     @type \Sl\SLPmtProto[]|\Google\Protobuf\Internal\RepeatedField $pmt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl.SLPatProto pat = 1;</code>
     * @return \Sl\SLPatProto
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * Generated from protobuf field <code>.sl.SLPatProto pat = 1;</code>
     * @param \Sl\SLPatProto $var
     * @return $this
     */
    public function setPat($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLPatProto::class);
        $this->pat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtProto pmt = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPmt()
    {
        return $this->pmt;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtProto pmt = 2;</code>
     * @param \Sl\SLPmtProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPmt($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLPmtProto::class);
        $this->pmt = $arr;

        return $this;
    }

}

