<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLInputSdtProto</code>
 */
class SLInputSdtProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl.SLSdtProto actual = 1;</code>
     */
    protected $actual = null;
    /**
     * Generated from protobuf field <code>.sl.SLSdtProto other = 2;</code>
     */
    protected $other = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLSdtProto $actual
     *     @type \Sl\SLSdtProto $other
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtProto actual = 1;</code>
     * @return \Sl\SLSdtProto
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtProto actual = 1;</code>
     * @param \Sl\SLSdtProto $var
     * @return $this
     */
    public function setActual($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLSdtProto::class);
        $this->actual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtProto other = 2;</code>
     * @return \Sl\SLSdtProto
     */
    public function getOther()
    {
        return $this->other;
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtProto other = 2;</code>
     * @param \Sl\SLSdtProto $var
     * @return $this
     */
    public function setOther($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLSdtProto::class);
        $this->other = $var;

        return $this;
    }

}

