<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_instance.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLInputProgramEncoderProto</code>
 */
class SLInputProgramEncoderProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sl.SLInputProgramProto input_program = 1;</code>
     */
    protected $input_program = null;
    /**
     * Generated from protobuf field <code>.sl.SLEncoderProto encoder = 2;</code>
     */
    protected $encoder = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLInputProgramProto $input_program
     *     @type \Sl\SLEncoderProto $encoder
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlGraphInstance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputProgramProto input_program = 1;</code>
     * @return \Sl\SLInputProgramProto
     */
    public function getInputProgram()
    {
        return $this->input_program;
    }

    /**
     * Generated from protobuf field <code>.sl.SLInputProgramProto input_program = 1;</code>
     * @param \Sl\SLInputProgramProto $var
     * @return $this
     */
    public function setInputProgram($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLInputProgramProto::class);
        $this->input_program = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLEncoderProto encoder = 2;</code>
     * @return \Sl\SLEncoderProto
     */
    public function getEncoder()
    {
        return $this->encoder;
    }

    /**
     * Generated from protobuf field <code>.sl.SLEncoderProto encoder = 2;</code>
     * @param \Sl\SLEncoderProto $var
     * @return $this
     */
    public function setEncoder($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLEncoderProto::class);
        $this->encoder = $var;

        return $this;
    }

}

