<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLLLDeviceInfoProto\SLLLDeviceTypeProto instead.
     * @deprecated
     */
    class SLLLDeviceInfoProto_SLLLDeviceTypeProto {}
}
class_exists(SLLLDeviceInfoProto\SLLLDeviceTypeProto::class);
@trigger_error('Sl\SLLLDeviceInfoProto_SLLLDeviceTypeProto is deprecated and will be removed in the next major release. Use Sl\SLLLDeviceInfoProto\SLLLDeviceTypeProto instead', E_USER_DEPRECATED);

