<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLLogicalChannelDescriptionProto\LogicalChannelProto instead.
     * @deprecated
     */
    class SLLogicalChannelDescriptionProto_LogicalChannelProto {}
}
class_exists(SLLogicalChannelDescriptionProto\LogicalChannelProto::class);
@trigger_error('Sl\SLLogicalChannelDescriptionProto_LogicalChannelProto is deprecated and will be removed in the next major release. Use Sl\SLLogicalChannelDescriptionProto\LogicalChannelProto instead', E_USER_DEPRECATED);

