<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLModelProto</code>
 */
class SLModelProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 1;</code>
     */
    protected $transport_stream_id = 0;
    /**
     * Generated from protobuf field <code>uint32 original_network_id = 2;</code>
     */
    protected $original_network_id = 0;
    /**
     * Generated from protobuf field <code>uint32 actual_network_id = 3;</code>
     */
    protected $actual_network_id = 0;
    /**
     * Generated from protobuf field <code>uint32 other_network_id = 4;</code>
     */
    protected $other_network_id = 0;
    /**
     * Generated from protobuf field <code>uint32 other_transport_stream_id = 5;</code>
     */
    protected $other_transport_stream_id = 0;
    /**
     * Generated from protobuf field <code>uint32 other_original_network_id = 6;</code>
     */
    protected $other_original_network_id = 0;
    /**
     * Generated from protobuf field <code>uint64 bitrate = 7;</code>
     */
    protected $bitrate = 0;
    /**
     * Generated from protobuf field <code>.sl.SLPatModelProto pat = 8;</code>
     */
    protected $pat = null;
    /**
     * Generated from protobuf field <code>.sl.SLCatModelProto cat = 9;</code>
     */
    protected $cat = null;
    /**
     * Generated from protobuf field <code>.sl.SLTdtModelProto tdt = 10;</code>
     */
    protected $tdt = null;
    /**
     * Generated from protobuf field <code>.sl.SLTotModelProto tot = 11;</code>
     */
    protected $tot = null;
    /**
     * Generated from protobuf field <code>.sl.SLSdtModelProto sdt = 12;</code>
     */
    protected $sdt = null;
    /**
     * Generated from protobuf field <code>.sl.SLNitModelProto nit = 13;</code>
     */
    protected $nit = null;
    /**
     * Generated from protobuf field <code>.sl.SLEitModelProto eit = 14;</code>
     */
    protected $eit = null;
    /**
     * Generated from protobuf field <code>.sl.SLOtherPidProto other_pid = 15;</code>
     */
    protected $other_pid = null;
    /**
     * Generated from protobuf field <code>bool vbr = 16;</code>
     */
    protected $vbr = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $transport_stream_id
     *     @type int $original_network_id
     *     @type int $actual_network_id
     *     @type int $other_network_id
     *     @type int $other_transport_stream_id
     *     @type int $other_original_network_id
     *     @type int|string $bitrate
     *     @type \Sl\SLPatModelProto $pat
     *     @type \Sl\SLCatModelProto $cat
     *     @type \Sl\SLTdtModelProto $tdt
     *     @type \Sl\SLTotModelProto $tot
     *     @type \Sl\SLSdtModelProto $sdt
     *     @type \Sl\SLNitModelProto $nit
     *     @type \Sl\SLEitModelProto $eit
     *     @type \Sl\SLOtherPidProto $other_pid
     *     @type bool $vbr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 1;</code>
     * @return int
     */
    public function getTransportStreamId()
    {
        return $this->transport_stream_id;
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTransportStreamId($var)
    {
        GPBUtil::checkUint32($var);
        $this->transport_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 original_network_id = 2;</code>
     * @return int
     */
    public function getOriginalNetworkId()
    {
        return $this->original_network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 original_network_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOriginalNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->original_network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 actual_network_id = 3;</code>
     * @return int
     */
    public function getActualNetworkId()
    {
        return $this->actual_network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 actual_network_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setActualNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->actual_network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 other_network_id = 4;</code>
     * @return int
     */
    public function getOtherNetworkId()
    {
        return $this->other_network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 other_network_id = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOtherNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->other_network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 other_transport_stream_id = 5;</code>
     * @return int
     */
    public function getOtherTransportStreamId()
    {
        return $this->other_transport_stream_id;
    }

    /**
     * Generated from protobuf field <code>uint32 other_transport_stream_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOtherTransportStreamId($var)
    {
        GPBUtil::checkUint32($var);
        $this->other_transport_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 other_original_network_id = 6;</code>
     * @return int
     */
    public function getOtherOriginalNetworkId()
    {
        return $this->other_original_network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 other_original_network_id = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOtherOriginalNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->other_original_network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bitrate = 7;</code>
     * @return int|string
     */
    public function getBitrate()
    {
        return $this->bitrate;
    }

    /**
     * Generated from protobuf field <code>uint64 bitrate = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBitrate($var)
    {
        GPBUtil::checkUint64($var);
        $this->bitrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLPatModelProto pat = 8;</code>
     * @return \Sl\SLPatModelProto
     */
    public function getPat()
    {
        return $this->pat;
    }

    /**
     * Generated from protobuf field <code>.sl.SLPatModelProto pat = 8;</code>
     * @param \Sl\SLPatModelProto $var
     * @return $this
     */
    public function setPat($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLPatModelProto::class);
        $this->pat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLCatModelProto cat = 9;</code>
     * @return \Sl\SLCatModelProto
     */
    public function getCat()
    {
        return $this->cat;
    }

    /**
     * Generated from protobuf field <code>.sl.SLCatModelProto cat = 9;</code>
     * @param \Sl\SLCatModelProto $var
     * @return $this
     */
    public function setCat($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLCatModelProto::class);
        $this->cat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTdtModelProto tdt = 10;</code>
     * @return \Sl\SLTdtModelProto
     */
    public function getTdt()
    {
        return $this->tdt;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTdtModelProto tdt = 10;</code>
     * @param \Sl\SLTdtModelProto $var
     * @return $this
     */
    public function setTdt($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLTdtModelProto::class);
        $this->tdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTotModelProto tot = 11;</code>
     * @return \Sl\SLTotModelProto
     */
    public function getTot()
    {
        return $this->tot;
    }

    /**
     * Generated from protobuf field <code>.sl.SLTotModelProto tot = 11;</code>
     * @param \Sl\SLTotModelProto $var
     * @return $this
     */
    public function setTot($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLTotModelProto::class);
        $this->tot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtModelProto sdt = 12;</code>
     * @return \Sl\SLSdtModelProto
     */
    public function getSdt()
    {
        return $this->sdt;
    }

    /**
     * Generated from protobuf field <code>.sl.SLSdtModelProto sdt = 12;</code>
     * @param \Sl\SLSdtModelProto $var
     * @return $this
     */
    public function setSdt($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLSdtModelProto::class);
        $this->sdt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLNitModelProto nit = 13;</code>
     * @return \Sl\SLNitModelProto
     */
    public function getNit()
    {
        return $this->nit;
    }

    /**
     * Generated from protobuf field <code>.sl.SLNitModelProto nit = 13;</code>
     * @param \Sl\SLNitModelProto $var
     * @return $this
     */
    public function setNit($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLNitModelProto::class);
        $this->nit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLEitModelProto eit = 14;</code>
     * @return \Sl\SLEitModelProto
     */
    public function getEit()
    {
        return $this->eit;
    }

    /**
     * Generated from protobuf field <code>.sl.SLEitModelProto eit = 14;</code>
     * @param \Sl\SLEitModelProto $var
     * @return $this
     */
    public function setEit($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLEitModelProto::class);
        $this->eit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sl.SLOtherPidProto other_pid = 15;</code>
     * @return \Sl\SLOtherPidProto
     */
    public function getOtherPid()
    {
        return $this->other_pid;
    }

    /**
     * Generated from protobuf field <code>.sl.SLOtherPidProto other_pid = 15;</code>
     * @param \Sl\SLOtherPidProto $var
     * @return $this
     */
    public function setOtherPid($var)
    {
        GPBUtil::checkMessage($var, \Sl\SLOtherPidProto::class);
        $this->other_pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool vbr = 16;</code>
     * @return bool
     */
    public function getVbr()
    {
        return $this->vbr;
    }

    /**
     * Generated from protobuf field <code>bool vbr = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setVbr($var)
    {
        GPBUtil::checkBool($var);
        $this->vbr = $var;

        return $this;
    }

}

