<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLNitProto</code>
 */
class SLNitProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     */
    protected $version_number = 0;
    /**
     * Generated from protobuf field <code>uint32 network_id = 2;</code>
     */
    protected $network_id = 0;
    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 3;</code>
     */
    private $descriptors;
    /**
     * Generated from protobuf field <code>repeated .sl.SLNitTransportStreamProto transport_stream = 4;</code>
     */
    private $transport_stream;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version_number
     *     @type int $network_id
     *     @type \Sl\SLDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $descriptors
     *     @type \Sl\SLNitTransportStreamProto[]|\Google\Protobuf\Internal\RepeatedField $transport_stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @return int
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 network_id = 2;</code>
     * @return int
     */
    public function getNetworkId()
    {
        return $this->network_id;
    }

    /**
     * Generated from protobuf field <code>uint32 network_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNetworkId($var)
    {
        GPBUtil::checkUint32($var);
        $this->network_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDescriptors()
    {
        return $this->descriptors;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 3;</code>
     * @param \Sl\SLDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDescriptors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLDescriptorProto::class);
        $this->descriptors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLNitTransportStreamProto transport_stream = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransportStream()
    {
        return $this->transport_stream;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLNitTransportStreamProto transport_stream = 4;</code>
     * @param \Sl\SLNitTransportStreamProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransportStream($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLNitTransportStreamProto::class);
        $this->transport_stream = $arr;

        return $this;
    }

}

