<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLParentalRatingDescriptorProto\RatingProto instead.
     * @deprecated
     */
    class SLParentalRatingDescriptorProto_RatingProto {}
}
class_exists(SLParentalRatingDescriptorProto\RatingProto::class);
@trigger_error('Sl\SLParentalRatingDescriptorProto_RatingProto is deprecated and will be removed in the next major release. Use Sl\SLParentalRatingDescriptorProto\RatingProto instead', E_USER_DEPRECATED);

