<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLPatProto</code>
 */
class SLPatProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     */
    protected $version_number = 0;
    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     */
    protected $transport_stream_id = 0;
    /**
     * Generated from protobuf field <code>repeated .sl.SLProgramMapProto program_map = 3;</code>
     */
    private $program_map;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version_number
     *     @type int $transport_stream_id
     *     @type \Sl\SLProgramMapProto[]|\Google\Protobuf\Internal\RepeatedField $program_map
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @return int
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     * @return int
     */
    public function getTransportStreamId()
    {
        return $this->transport_stream_id;
    }

    /**
     * Generated from protobuf field <code>uint32 transport_stream_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTransportStreamId($var)
    {
        GPBUtil::checkUint32($var);
        $this->transport_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLProgramMapProto program_map = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProgramMap()
    {
        return $this->program_map;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLProgramMapProto program_map = 3;</code>
     * @param \Sl\SLProgramMapProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProgramMap($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLProgramMapProto::class);
        $this->program_map = $arr;

        return $this;
    }

}

