<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLPmtProto</code>
 */
class SLPmtProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     */
    protected $version_number = 0;
    /**
     * Generated from protobuf field <code>uint32 program_number = 2;</code>
     */
    protected $program_number = 0;
    /**
     * Generated from protobuf field <code>uint32 pid_pmt = 3;</code>
     */
    protected $pid_pmt = 0;
    /**
     * Generated from protobuf field <code>uint32 PCR_PID = 4;</code>
     */
    protected $PCR_PID = 0;
    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 5;</code>
     */
    private $descriptors;
    /**
     * Generated from protobuf field <code>repeated .sl.SLStreamMapProto stream_map = 6;</code>
     */
    private $stream_map;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version_number
     *     @type int $program_number
     *     @type int $pid_pmt
     *     @type int $PCR_PID
     *     @type \Sl\SLDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $descriptors
     *     @type \Sl\SLStreamMapProto[]|\Google\Protobuf\Internal\RepeatedField $stream_map
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlMpegTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @return int
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 program_number = 2;</code>
     * @return int
     */
    public function getProgramNumber()
    {
        return $this->program_number;
    }

    /**
     * Generated from protobuf field <code>uint32 program_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProgramNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->program_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pid_pmt = 3;</code>
     * @return int
     */
    public function getPidPmt()
    {
        return $this->pid_pmt;
    }

    /**
     * Generated from protobuf field <code>uint32 pid_pmt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPidPmt($var)
    {
        GPBUtil::checkUint32($var);
        $this->pid_pmt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 PCR_PID = 4;</code>
     * @return int
     */
    public function getPCRPID()
    {
        return $this->PCR_PID;
    }

    /**
     * Generated from protobuf field <code>uint32 PCR_PID = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPCRPID($var)
    {
        GPBUtil::checkUint32($var);
        $this->PCR_PID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDescriptors()
    {
        return $this->descriptors;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLDescriptorProto descriptors = 5;</code>
     * @param \Sl\SLDescriptorProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDescriptors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLDescriptorProto::class);
        $this->descriptors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLStreamMapProto stream_map = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStreamMap()
    {
        return $this->stream_map;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLStreamMapProto stream_map = 6;</code>
     * @param \Sl\SLStreamMapProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStreamMap($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLStreamMapProto::class);
        $this->stream_map = $arr;

        return $this;
    }

}

