<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sl.SLPmtsModelProto</code>
 */
class SLPmtsModelProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtModelProto pmts = 1;</code>
     */
    private $pmts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLPmtModelProto[]|\Google\Protobuf\Internal\RepeatedField $pmts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtModelProto pmts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPmts()
    {
        return $this->pmts;
    }

    /**
     * Generated from protobuf field <code>repeated .sl.SLPmtModelProto pmts = 1;</code>
     * @param \Sl\SLPmtModelProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPmts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLPmtModelProto::class);
        $this->pmts = $arr;

        return $this;
    }

}

