<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_graph_service.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLReserveProto\SLStateProto instead.
     * @deprecated
     */
    class SLReserveProto_SLStateProto {}
}
class_exists(SLReserveProto\SLStateProto::class);
@trigger_error('Sl\SLReserveProto_SLStateProto is deprecated and will be removed in the next major release. Use Sl\SLReserveProto\SLStateProto instead', E_USER_DEPRECATED);

