<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_remuxer_model.proto

namespace Sl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;/////////////////////////////////////////////////////////////////////////////
 * SDT
 *
 * Generated from protobuf message <code>sl.SLSdtsSdsModel</code>
 */
class SLSdtsSdsModel extends \Google\Protobuf\Internal\Message
{
    /**
     * src number, dst number
     *
     * Generated from protobuf field <code>repeated .sl.SLPairModel src_dst = 1;</code>
     */
    private $src_dst;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sl\SLPairModel[]|\Google\Protobuf\Internal\RepeatedField $src_dst
     *           src number, dst number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlRemuxerModel::initOnce();
        parent::__construct($data);
    }

    /**
     * src number, dst number
     *
     * Generated from protobuf field <code>repeated .sl.SLPairModel src_dst = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSrcDst()
    {
        return $this->src_dst;
    }

    /**
     * src number, dst number
     *
     * Generated from protobuf field <code>repeated .sl.SLPairModel src_dst = 1;</code>
     * @param \Sl\SLPairModel[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSrcDst($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sl\SLPairModel::class);
        $this->src_dst = $arr;

        return $this;
    }

}

