<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl_mpeg_ts.proto

namespace Sl;

if (false) {
    /**
     * This class is deprecated. Use Sl\SLServiceListDescriptorProto\ServiceProto instead.
     * @deprecated
     */
    class SLServiceListDescriptorProto_ServiceProto {}
}
class_exists(SLServiceListDescriptorProto\ServiceProto::class);
@trigger_error('Sl\SLServiceListDescriptorProto_ServiceProto is deprecated and will be removed in the next major release. Use Sl\SLServiceListDescriptorProto\ServiceProto instead', E_USER_DEPRECATED);

